.TH ELKS-SMS 1 "JUNE 2016" "elkme 0.1" "User Manuals"
.SH NAME
elks sms

.SH SYNOPSIS
TODO

.SH DESCRIPTION
.B elks sms
is used to send outgoing SMS and read incoming SMS from the command-line
command line using the 46elks API from https://46elks.com

.SH OPTIONS
.IP "-h, --help"
Show an overview of the features of Elks SMS and then exits
.IP "--version"
Show the current version of elks running

.SH COMMANDS
.IP new
Send a new SMS to 

.IP list
See previously sent and received SMS

.SH COPYRIGHT
Licensed under the MIT license.
Copyright (c) 2015 46elks AB <hello@46elks.com>

This tool is developed by Emil Tullstedt <emil@46elks.com> and has secret
elk superpowers.

.SH FILES
See \fBelkme(1)\fR and \fBelkme(5)\fR
