.TH ELKS 1 "JUNE 2016" "elkme 0.1" "User Manuals"
.SH NAME
elks \- 46elks CLI

.SH SYNOPSIS
TODO

.SH DESCRIPTION
.B elkme
is an application for sending text messages with the
command line using the 46elks API from https://46elks.com

.SH OPTIONS
.IP "-h, --help"
Show an overview of the features of elkme and then exits
.IP "--version"
Show the current version of elks running

.SH COMMANDS
.IP "elks status(1)"
See information about the currently authenticated 46elks account

.IP "elks list-sms(1)"
See sent and received SMS

.IP "elks list-mms(1)"
See sent and received MMS

.IP "elks list-calls(1)"
Initialize phone calls, see call log

.IP "elks recordings(1)"
Download and play call recordings

.IP "elks images(1)"
Download image attachements

.IP "elks numbers(1)"
Purchase, list and modify 46elks numbers

.IP "elks billing(1)"
See the credit transactions log

.IP "elks subaccounts(1)"
Create, list and modify subaccounts

.IP "elks setup(1)"
Interactive initialization of 46elks configuration

.IP "elks logs(1)"
Access your 46elks logs

.IP "elks debug(1)"
The 46elks debugger with integrated logs and debugging tools

.SH COPYRIGHT
Licensed under the MIT license.
Copyright (c) 2015 46elks AB <hello@46elks.com>

This tool is developed by Emil Tullstedt <emil@46elks.com> and has secret
elk superpowers.

.SH FILES
See \fBelkme(1)\fR and \fBelkme(5)\fR
